import {Inject, Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { User, UserDocument } from '../user.entity';
import {RandomUsernameGenerator} from '../utils/random-username.generator';
import {JwtService} from "@nestjs/jwt";

@Injectable()
export class UserService {
    @Inject(RandomUsernameGenerator)
    private readonly randomUsernameGenerator: RandomUsernameGenerator;

    @Inject(JwtService)
    private readonly jwtService: JwtService;

    constructor(
        @InjectModel(User.name) private readonly userRepository: Model<UserDocument>
    ) {}

    async createRandomUser(): Promise<UserDocument> {
        const user = new User();
        user.username = this.randomUsernameGenerator.generate();
        user.isAutoGenerated = true;

        return await this.userRepository.create(user);
    }

    getJwt(user: UserDocument): string {
        const payload = { username: user.username, sub: user._id };

        return this.jwtService.sign(payload);
    }
}