import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type UserDocument = User & Document;

@Schema({
    timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt' },
})
export class User {
    @Prop({ required: true })
    username: string;

    @Prop({ required: false })
    password: string;

    @Prop({ required: true })
    isAutoGenerated: boolean;
}

export const UserSchema = SchemaFactory.createForClass(User);
